# Generated by Django 4.2.1 on 2023-05-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('department', models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology'), ('IS', 'Information Systems'), ('DS', 'Decision Support'), ('AI', 'Artificial Intellegience')], max_length=25)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('FM', 'Female')], max_length=10)),
                ('level', models.CharField(choices=[('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4')], max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'In Active')], max_length=10)),
            ],
        ),
    ]
