# Generated by Django 4.2.1 on 2023-05-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_mobile_alter_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.CharField(max_length=25),
        ),
    ]
